baseURL = "http://example.com/"
languageCode = "en-us"
title = "EchoSlate"
theme = "ananke"  
defaultContentLanguage = "en"
enableMissingTranslationPlaceholders = true  # Helps identify missing translations

# Language Configuration
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "EchoSlate"
    contentDir = "content/en"
    [languages.en.params]
      description = "A digital portfolio website to showcase resumes and projects."

  [languages.es]
    languageName = "Español"
    weight = 2
    title = "EchoSlate"
    contentDir = "content/es"
    [languages.es.params]
      description = "Un sitio web de portafolio digital para mostrar currículums y proyectos."

# Menus Configuration
[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "users"
    name = "Users"
    url = "/users/"
    weight = 2

  [[menu.main]]
    identifier = "edit"
    name = "Edit"
    url = "/edit/"
    weight = 3

  [[menu.main]]
    identifier = "upload"
    name = "Upload"
    url = "/upload/"
    weight = 4

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 6

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 7

# Markup Configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false  # Set to true to disable CSS classes for code highlighting
